# Generated by Django 3.2.13 on 2022-05-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(auto_now=True, verbose_name='Data de Entrada')),
                ('date_pay', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('date_out', models.DateTimeField(verbose_name='Data de Saida')),
                ('value', models.IntegerField(verbose_name='Valor Pago')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.estacionamento')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculos')),
            ],
        ),
    ]
