# Generated by Django 3.2.13 on 2022-05-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_vagas_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vagas',
            options={'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
    ]
