# Generated by Django 3.2.13 on 2022-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_alter_vagas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saida'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='date_pay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Pago'),
        ),
    ]
