# Generated by Django 3.2.13 on 2022-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_auto_20220518_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
    ]
