# Generated by Django 3.2.13 on 2022-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_alter_vagas_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='is_ativa',
            field=models.BooleanField(default=True, verbose_name='Está ocupada?'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Está paga?'),
        ),
    ]
