# Generated by Django 3.2.13 on 2022-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('total_vagas_comuns', models.IntegerField(verbose_name='Total de vagas comuns')),
                ('total_vagas_especiais', models.IntegerField(verbose_name='Total de vagas especiais')),
                ('vagas_livres_especiais', models.IntegerField(verbose_name='Vagas especiais livres')),
                ('vagas_livres_comuns', models.IntegerField(verbose_name='Vagas comuns livres')),
            ],
            options={
                'verbose_name_plural': 'Estacionamentos',
            },
        ),
    ]
