# Generated by Django 3.2.13 on 2022-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_alter_estacionamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
