# Generated by Django 3.2.13 on 2022-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa')),
                ('is_especial', models.BooleanField(default=False, verbose_name='Necessita vaga especial?')),
                ('is_plan', models.BooleanField(default=False, verbose_name='Possui plano ativo?')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
