# Generated by Django 3.2.13 on 2022-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name_plural': 'Veiculos'},
        ),
    ]
